"""Initial migration

Revision ID: 76aef5410a73
Revises: 
Create Date: 2025-12-16 22:42:57.911353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76aef5410a73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeline_items')
    op.drop_table('checklist_items')
    op.drop_table('activities')
    op.drop_table('projects')
    op.drop_table('files')
    op.drop_table('tasks')
    op.drop_table('clients')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=240), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('assignee', sa.VARCHAR(length=80), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), nullable=False),
    sa.Column('tags', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=260), nullable=False),
    sa.Column('stored_path', sa.VARCHAR(length=520), nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=120), nullable=True),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=False),
    sa.Column('uploader', sa.VARCHAR(length=120), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=240), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('location', sa.VARCHAR(length=120), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('risk', sa.VARCHAR(length=20), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('target_close_date', sa.DATE(), nullable=True),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('bg_color', sa.VARCHAR(length=20), server_default=sa.text("'#0b1220'"), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('actor', sa.VARCHAR(length=120), nullable=False),
    sa.Column('verb', sa.VARCHAR(length=120), nullable=False),
    sa.Column('detail', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('stage', sa.VARCHAR(length=40), nullable=False),
    sa.Column('label', sa.VARCHAR(length=300), nullable=False),
    sa.Column('is_done', sa.BOOLEAN(), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=240), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('kind', sa.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
